export default [
  {
    OrderId: 11142,
    CustomerReference: 'MEREP',
    CompanyName: 'Mère Paillarde',
    ContactName: 'Jean Fresnière',
    Employee: 'Michael Suyama',
    InvoicedCost: 855.45,
    ItemCount: 10,
    ChangeLastOrder: 2,
    ItemCost: 95.05,
    OrderCost: 950.5,
    PackageCost: 12.7,
    OrderDate: 43503,
    RequiredDate: 43531,
    ShippedDate: 43506,
    ShipVia: 'Federal Shipping',
    Freight: 4.07,
    ShipName: 'Mère Paillarde',
    ShipAddress: '43 rue St. Laurent',
    ShipCity: 'Montréal',
    ShipRegion: 'Quebec',
    ShipPostalCode: 'H1J 1C3',
    ShipCountry: 'Canada',
    ArriveOnTime: 1,
  },
  {
    OrderId: 11140,
    CustomerReference: 'TOMSP',
    CompanyName: 'Toms Spezialitäten',
    ContactName: 'Karin Josephs',
    Employee: 'Janet Leverling',
    InvoicedCost: 738.7263,
    ItemCount: 13,
    ChangeLastOrder: -12,
    ItemCost: 55.17,
    OrderCost: 717.21,
    PackageCost: 14.95,
    OrderDate: 43502,
    RequiredDate: 43530,
    ShippedDate: 43510,
    ShipVia: 'United Package',
    Freight: 8.24,
    ShipName: 'Toms Spezialitäten',
    ShipAddress: 'Luisenstr. 48',
    ShipCity: 'Münster',
    ShipRegion: '',
    ShipPostalCode: 44087,
    ShipCountry: 'Germany',
    ArriveOnTime: 1,
  },
  {
    OrderId: 11138,
    CustomerReference: 'WARTH',
    CompanyName: 'Wartian Herkku',
    ContactName: 'Pirkko Koskitalo',
    Employee: 'Laura Callahan',
    InvoicedCost: 1060.1955,
    ItemCount: 13,
    ChangeLastOrder: 41,
    ItemCost: 77.67,
    OrderCost: 1009.71,
    PackageCost: 18.577,
    OrderDate: 43501,
    RequiredDate: 43529,
    ShippedDate: 43508,
    ShipVia: 'Speedy Express',
    Freight: 19.97,
    ShipName: 'Wartian Herkku',
    ShipAddress: 'Torikatu 38',
    ShipCity: 'Oulu',
    ShipRegion: '',
    ShipPostalCode: 90110,
    ShipCountry: 'Finland',
    ArriveOnTime: 1,
  },
  {
    OrderId: 11137,
    CustomerReference: 'BLONP',
    CompanyName: 'Blondel père et fils',
    ContactName: 'Frédérique Citeaux',
    Employee: 'Janet Leverling',
    InvoicedCost: 874.8739999999999,
    ItemCount: 14,
    ChangeLastOrder: 4,
    ItemCost: 54.34,
    OrderCost: 760.76,
    PackageCost: 7.5600000000000005,
    OrderDate: 43501,
    RequiredDate: 43529,
    ShippedDate: 43507,
    ShipVia: 'United Package',
    Freight: 156.66,
    ShipName: 'Blondel père et fils',
    ShipAddress: '24, place Kléber',
    ShipCity: 'Strasbourg',
    ShipRegion: '',
    ShipPostalCode: 67000,
    ShipCountry: 'France',
    ArriveOnTime: 0,
  },
  {
    OrderId: 11136,
    CustomerReference: 'CONSH',
    CompanyName: 'Consolidated Holdings',
    ContactName: 'Elizabeth Brown',
    Employee: 'Laura Callahan',
    InvoicedCost: 815.4,
    ItemCount: 10,
    ChangeLastOrder: -3,
    ItemCost: 90.6,
    OrderCost: 906,
    PackageCost: 12.7,
    OrderDate: 43500,
    RequiredDate: 43542,
    ShippedDate: 43503,
    ShipVia: 'United Package',
    Freight: 9.21,
    ShipName: 'Consolidated Holdings',
    ShipAddress: 'Berkeley Gardens, 12  Brewery',
    ShipCity: 'London',
    ShipRegion: '',
    ShipPostalCode: 'WX1 6LT',
    ShipCountry: 'UK',
    ArriveOnTime: 1,
  },
];
