// constants used in Config
export const SYSTEM = 'System';
export const GRID = 'Grid';
export const POPUP = 'Popup';
export const TEAM_SHARING = 'TeamSharing';
export const BULK_UPDATE = 'BulkUpdate';
export const USER_INTERFACE = 'UserInterface';
export const ENTITLEMENTS = 'Entitlements';
export const APPLICATION = 'Application';
export const NAMED_FILTER = 'NamedFilter';
export const ACTION_COLUMN = 'ActionColumn';
export const SPARKLINE_COLUMN = 'SparklineColumn';
export const CELL_SUMMARY = 'CellSummary';
export const PARTNER = 'Partner';
export const SYSTEM_FILTER = 'SystemFilter';
export const PLUGINS = 'Plugins';
