import { RedComponentComponent } from './red-component/red-component.component';

export default [
  {
    headerName: 'Order Id',
    field: 'OrderId',
    editable: true,
    cellClass: 'number-cell',
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Cust. Ref',
    field: 'CustomerReference',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Company',
    field: 'CompanyName',
    editable: true,
    filter: true,
    sortable: true,
    cellRendererFramework: RedComponentComponent,
    enableRowGroup: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Contact',
    field: 'ContactName',
    filter: true,
    sortable: true,
    enableRowGroup: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Employee',
    field: 'Employee',
    filter: 'text',
    editable: true,
    sortable: true,
    enableRowGroup: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Order Date',
    field: 'OrderDate',
    editable: true,
    cellEditorParams: {
      useFormatter: true,
    },
    filter: true,
    sortable: true,
    type: 'abColDefDate',
  },
  {
    headerName: 'Invoiced',
    field: 'InvoicedCost',
    cellClass: 'number-cell',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Order Cost',
    field: 'OrderCost',
    cellClass: 'number-cell',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Package Cost',
    field: 'PackageCost',
    cellClass: 'number-cell',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Item Cost',
    field: 'ItemCost',
    cellClass: 'number-cell',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Item Count',
    field: 'ItemCount',
    cellClass: 'number-cell',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Change Last Order',
    field: 'ChangeLastOrder',
    cellClass: 'number-cell',
    editable: true,
    filter: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Ship Via',
    field: 'ShipVia',
    filter: 'text',
    editable: true,
    sortable: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Freight',
    field: 'Freight',
    cellClass: 'number-cell',
    editable: true,
    sortable: true,
    type: 'abColDefNumber',
  },
  {
    headerName: 'Ship Name',
    field: 'ShipName',
    columnGroupShow: 'open',
    editable: true,
    sortable: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Ship Country',
    field: 'ShipCountry',
    filter: 'text',
    editable: true,
    sortable: true,
    type: 'abColDefString',
  },
  {
    headerName: 'Shipped Date',
    field: 'ShippedDate',
    editable: true,
    cellEditorParams: {
      useFormatter: true,
    },
    filter: true,
    sortable: true,
    type: 'abColDefDate',
  },
];
