export const CustomSortStrategyId :string = "CustomSort"
export const SmartEditStrategyId :string = "SmartEdit"
export const ShortcutStrategyId :string = "Shortcut"
export const UserDataManagementStrategyId :string = "UserDataManagement"
export const PlusMinusStrategyId :string = "PlusMinus"
export const ColumnChooserStrategyId :string = "ColumnChooser"