[
  {
    colId: 'country',
    hide: false,
    aggFunc: 'sum',
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'currency',
    hide: false,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'notional',
    hide: false,
    aggFunc: 'sum',
    width: 433,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'tradeId',
    hide: false,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'counterparty',
    hide: false,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: '0',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'changeOnYear',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'ask',
    hide: true,
    aggFunc: 'sum',
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'bid',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'isLive',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'amount',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'stars',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'tradeDate',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'bloombergAsk',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'status',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'bidOfferSpread',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'price',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'dv01',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'moodysRating',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'sandpRating',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'settlementDate',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'lastUpdatedBy',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'lastUpdated',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'percentChange',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
  {
    colId: 'deskId',
    hide: true,
    aggFunc: null,
    width: 200,
    pivotIndex: null,
    pinned: null,
    rowGroupIndex: null,
    flex: 0,
  },
];
