module.exports = {
  src: ['./src/'],
  mode: 'modules',
  includeDeclarations: false,
  exclude: [
    './src/agGrid/**/*',
    './src/View/**/*',
    './src/components/**/*',
    './src/Redux/**/*',
    './src/Strategy/**/*',
    './src/Utilities/**/*',
    './src/AdaptableInterfaces/**/*',
    './src/fonts/**/*',
    './src/themes/**/*',
    './src/Api/Implementation/**/*',
    './src/env.ts',
    './src/theme.ts',
    './src/types.ts',
    './src/PredefinedConfig/AdaptableState.ts',
  ],
  tsconfig: 'tsconfig.json',
  out: './apidoc',
  excludePrivate: true,
  excludeProtected: true,
  excludeExternals: true,
  excludeNotExported: true,
  readme: 'HelpREADME.md',
  name: 'Adaptable Developer Documentation',
  ignoreCompilerErrors: true,
  plugin: 'none',
  listInvalidSymbolLinks: true,
};
